
package com.xmlws.agent.back;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackendServicePort", targetNamespace = "admin.xmlws.com/backend")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackendServicePort {


    /**
     * 
     * @param updateRezervacijaRequest
     * @return
     *     returns com.xmlws.admin.backend.UpdateRezervacijaResponse
     */
    @WebMethod
    @WebResult(name = "updateRezervacijaResponse", targetNamespace = "admin.xmlws.com/backend", partName = "updateRezervacijaResponse")
    public UpdateRezervacijaResponse updateRezervacija(
        @WebParam(name = "updateRezervacijaRequest", targetNamespace = "admin.xmlws.com/backend", partName = "updateRezervacijaRequest")
        UpdateRezervacijaRequest updateRezervacijaRequest);

    /**
     * 
     * @param getRezervacijaRequest
     * @return
     *     returns com.xmlws.admin.backend.GetRezervacijaResponse
     */
    @WebMethod
    @WebResult(name = "getRezervacijaResponse", targetNamespace = "admin.xmlws.com/backend", partName = "getRezervacijaResponse")
    public GetRezervacijaResponse getRezervacija(
        @WebParam(name = "getRezervacijaRequest", targetNamespace = "admin.xmlws.com/backend", partName = "getRezervacijaRequest")
        GetRezervacijaRequest getRezervacijaRequest);

    /**
     * 
     * @param addPonudaRequest
     * @return
     *     returns com.xmlws.admin.backend.AddPonudaResponse
     */
    @WebMethod
    @WebResult(name = "addPonudaResponse", targetNamespace = "admin.xmlws.com/backend", partName = "addPonudaResponse")
    public AddPonudaResponse addPonuda(
        @WebParam(name = "addPonudaRequest", targetNamespace = "admin.xmlws.com/backend", partName = "addPonudaRequest")
        AddPonudaRequest addPonudaRequest);

    /**
     * 
     * @param getSmestajRequest
     * @return
     *     returns com.xmlws.admin.backend.GetSmestajResponse
     */
    @WebMethod
    @WebResult(name = "getSmestajResponse", targetNamespace = "admin.xmlws.com/backend", partName = "getSmestajResponse")
    public GetSmestajResponse getSmestaj(
        @WebParam(name = "getSmestajRequest", targetNamespace = "admin.xmlws.com/backend", partName = "getSmestajRequest")
        GetSmestajRequest getSmestajRequest);

    /**
     * 
     * @param addSmestajRequest
     * @return
     *     returns com.xmlws.admin.backend.AddSmestajResponse
     */
    @WebMethod
    @WebResult(name = "addSmestajResponse", targetNamespace = "admin.xmlws.com/backend", partName = "addSmestajResponse")
    public AddSmestajResponse addSmestaj(
        @WebParam(name = "addSmestajRequest", targetNamespace = "admin.xmlws.com/backend", partName = "addSmestajRequest")
        AddSmestajRequest addSmestajRequest);

}
