
package com.xmlws.agent.back;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BackendServicePortService", targetNamespace = "admin.xmlws.com/backend", wsdlLocation = "http://localhost:8085/ws/mojismestaji.wsdl")
public class BackendServicePortService
    extends Service
{

    private final static URL BACKENDSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKENDSERVICEPORTSERVICE_EXCEPTION;
    private final static QName BACKENDSERVICEPORTSERVICE_QNAME = new QName("admin.xmlws.com/backend", "BackendServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/ws/mojismestaji.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BACKENDSERVICEPORTSERVICE_WSDL_LOCATION = url;
        BACKENDSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public BackendServicePortService() {
        super(__getWsdlLocation(), BACKENDSERVICEPORTSERVICE_QNAME);
    }

    public BackendServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKENDSERVICEPORTSERVICE_QNAME, features);
    }

    public BackendServicePortService(URL wsdlLocation) {
        super(wsdlLocation, BACKENDSERVICEPORTSERVICE_QNAME);
    }

    public BackendServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKENDSERVICEPORTSERVICE_QNAME, features);
    }

    public BackendServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackendServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BackendServicePort
     */
    @WebEndpoint(name = "BackendServicePortSoap11")
    public BackendServicePort getBackendServicePortSoap11() {
        return super.getPort(new QName("admin.xmlws.com/backend", "BackendServicePortSoap11"), BackendServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackendServicePort
     */
    @WebEndpoint(name = "BackendServicePortSoap11")
    public BackendServicePort getBackendServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("admin.xmlws.com/backend", "BackendServicePortSoap11"), BackendServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKENDSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw BACKENDSERVICEPORTSERVICE_EXCEPTION;
        }
        return BACKENDSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
