
package com.xmlws.agent.back;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackendServicePort", targetNamespace = "admin.xmlws.com/backend")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackendServicePort {


    /**
     * 
     * @param addSmestajRequest
     * @return
     *     returns com.xmlws.admin.backend.AddSmestajResponse
     */
    @WebMethod
    @WebResult(name = "addSmestajResponse", targetNamespace = "admin.xmlws.com/backend", partName = "addSmestajResponse")
    public AddSmestajResponse addSmestaj(
        @WebParam(name = "addSmestajRequest", targetNamespace = "admin.xmlws.com/backend", partName = "addSmestajRequest")
        AddSmestajRequest addSmestajRequest);

}
