//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.03 at 12:54:46 PM CEST 
//


package com.xmlws.admin.backend;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xmlws.admin.backend package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xmlws.admin.backend
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddImageRequest }
     * 
     */
    public AddImageRequest createAddImageRequest() {
        return new AddImageRequest();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link GetAllPonudaRequest }
     * 
     */
    public GetAllPonudaRequest createGetAllPonudaRequest() {
        return new GetAllPonudaRequest();
    }

    /**
     * Create an instance of {@link AddPorukaRequest }
     * 
     */
    public AddPorukaRequest createAddPorukaRequest() {
        return new AddPorukaRequest();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link AddPorukaResponse }
     * 
     */
    public AddPorukaResponse createAddPorukaResponse() {
        return new AddPorukaResponse();
    }

    /**
     * Create an instance of {@link GetAllSmestajResponse }
     * 
     */
    public GetAllSmestajResponse createGetAllSmestajResponse() {
        return new GetAllSmestajResponse();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link UpdateRezervacijaRequest }
     * 
     */
    public UpdateRezervacijaRequest createUpdateRezervacijaRequest() {
        return new UpdateRezervacijaRequest();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaRequest }
     * 
     */
    public GetAllRezervacijaRequest createGetAllRezervacijaRequest() {
        return new GetAllRezervacijaRequest();
    }

    /**
     * Create an instance of {@link AddPonudaResponse }
     * 
     */
    public AddPonudaResponse createAddPonudaResponse() {
        return new AddPonudaResponse();
    }

    /**
     * Create an instance of {@link Ponuda }
     * 
     */
    public Ponuda createPonuda() {
        return new Ponuda();
    }

    /**
     * Create an instance of {@link GetRezervacijaResponse }
     * 
     */
    public GetRezervacijaResponse createGetRezervacijaResponse() {
        return new GetRezervacijaResponse();
    }

    /**
     * Create an instance of {@link AddSmestajResponse }
     * 
     */
    public AddSmestajResponse createAddSmestajResponse() {
        return new AddSmestajResponse();
    }

    /**
     * Create an instance of {@link GetPonudaResponse }
     * 
     */
    public GetPonudaResponse createGetPonudaResponse() {
        return new GetPonudaResponse();
    }

    /**
     * Create an instance of {@link UpdateRezervacijaResponse }
     * 
     */
    public UpdateRezervacijaResponse createUpdateRezervacijaResponse() {
        return new UpdateRezervacijaResponse();
    }

    /**
     * Create an instance of {@link GetAllPorukeResponse }
     * 
     */
    public GetAllPorukeResponse createGetAllPorukeResponse() {
        return new GetAllPorukeResponse();
    }

    /**
     * Create an instance of {@link AddPonudaRequest }
     * 
     */
    public AddPonudaRequest createAddPonudaRequest() {
        return new AddPonudaRequest();
    }

    /**
     * Create an instance of {@link GetRezervacijaRequest }
     * 
     */
    public GetRezervacijaRequest createGetRezervacijaRequest() {
        return new GetRezervacijaRequest();
    }

    /**
     * Create an instance of {@link GetAllSmestajRequest }
     * 
     */
    public GetAllSmestajRequest createGetAllSmestajRequest() {
        return new GetAllSmestajRequest();
    }

    /**
     * Create an instance of {@link GetAllSmResponse }
     * 
     */
    public GetAllSmResponse createGetAllSmResponse() {
        return new GetAllSmResponse();
    }

    /**
     * Create an instance of {@link AddSmestajRequest }
     * 
     */
    public AddSmestajRequest createAddSmestajRequest() {
        return new AddSmestajRequest();
    }

    /**
     * Create an instance of {@link GetAllPorukeRequest }
     * 
     */
    public GetAllPorukeRequest createGetAllPorukeRequest() {
        return new GetAllPorukeRequest();
    }

    /**
     * Create an instance of {@link GetPonudaRequest }
     * 
     */
    public GetPonudaRequest createGetPonudaRequest() {
        return new GetPonudaRequest();
    }

    /**
     * Create an instance of {@link AddImageResponse }
     * 
     */
    public AddImageResponse createAddImageResponse() {
        return new AddImageResponse();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaResponse }
     * 
     */
    public GetAllRezervacijaResponse createGetAllRezervacijaResponse() {
        return new GetAllRezervacijaResponse();
    }

    /**
     * Create an instance of {@link GetAllPonudaResponse }
     * 
     */
    public GetAllPonudaResponse createGetAllPonudaResponse() {
        return new GetAllPonudaResponse();
    }

    /**
     * Create an instance of {@link GetAllSmRequest }
     * 
     */
    public GetAllSmRequest createGetAllSmRequest() {
        return new GetAllSmRequest();
    }

    /**
     * Create an instance of {@link GetSmestajResponse }
     * 
     */
    public GetSmestajResponse createGetSmestajResponse() {
        return new GetSmestajResponse();
    }

    /**
     * Create an instance of {@link GetSmestajRequest }
     * 
     */
    public GetSmestajRequest createGetSmestajRequest() {
        return new GetSmestajRequest();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link Sifrarnik }
     * 
     */
    public Sifrarnik createSifrarnik() {
        return new Sifrarnik();
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link RegistrovaniKorisnik }
     * 
     */
    public RegistrovaniKorisnik createRegistrovaniKorisnik() {
        return new RegistrovaniKorisnik();
    }

}
