//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 11:08:38 AM CEST 
//


package com.xmlws.admin.backend;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xmlws.admin.backend package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xmlws.admin.backend
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddSmestajRequest }
     * 
     */
    public AddSmestajRequest createAddSmestajRequest() {
        return new AddSmestajRequest();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link UpdateRezervacijaResponse }
     * 
     */
    public UpdateRezervacijaResponse createUpdateRezervacijaResponse() {
        return new UpdateRezervacijaResponse();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link AddPonudaResponse }
     * 
     */
    public AddPonudaResponse createAddPonudaResponse() {
        return new AddPonudaResponse();
    }

    /**
     * Create an instance of {@link Ponuda }
     * 
     */
    public Ponuda createPonuda() {
        return new Ponuda();
    }

    /**
     * Create an instance of {@link GetRezervacijaResponse }
     * 
     */
    public GetRezervacijaResponse createGetRezervacijaResponse() {
        return new GetRezervacijaResponse();
    }

    /**
     * Create an instance of {@link AddPonudaRequest }
     * 
     */
    public AddPonudaRequest createAddPonudaRequest() {
        return new AddPonudaRequest();
    }

    /**
     * Create an instance of {@link UpdateRezevacijaRequest }
     * 
     */
    public UpdateRezevacijaRequest createUpdateRezevacijaRequest() {
        return new UpdateRezevacijaRequest();
    }

    /**
     * Create an instance of {@link GetSmestajResponse }
     * 
     */
    public GetSmestajResponse createGetSmestajResponse() {
        return new GetSmestajResponse();
    }

    /**
     * Create an instance of {@link AddSmestajResponse }
     * 
     */
    public AddSmestajResponse createAddSmestajResponse() {
        return new AddSmestajResponse();
    }

    /**
     * Create an instance of {@link GetRezervacijaRequest }
     * 
     */
    public GetRezervacijaRequest createGetRezervacijaRequest() {
        return new GetRezervacijaRequest();
    }

    /**
     * Create an instance of {@link GetSmestajRequest }
     * 
     */
    public GetSmestajRequest createGetSmestajRequest() {
        return new GetSmestajRequest();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link RegistrovaniKorisnik }
     * 
     */
    public RegistrovaniKorisnik createRegistrovaniKorisnik() {
        return new RegistrovaniKorisnik();
    }

}
