//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.27 at 09:34:50 AM CEST 
//


package com.xmlws.admin.backend;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Rezervacija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rezervacija">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Korisnik" type="{admin.xmlws.com/backend}Korisnik"/>
 *         &lt;element name="Potvrdjeno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Datum_realizacije" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rezervacija", propOrder = {
    "korisnik",
    "potvrdjeno",
    "datumRealizacije",
    "id"
})
public class Rezervacija {

    @XmlElement(name = "Korisnik", required = true)
    protected Korisnik korisnik;
    @XmlElement(name = "Potvrdjeno")
    protected boolean potvrdjeno;
    @XmlElement(name = "Datum_realizacije", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumRealizacije;
    protected long id;

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link Korisnik }
     *     
     */
    public Korisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Korisnik }
     *     
     */
    public void setKorisnik(Korisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the potvrdjeno property.
     * 
     */
    public boolean isPotvrdjeno() {
        return potvrdjeno;
    }

    /**
     * Sets the value of the potvrdjeno property.
     * 
     */
    public void setPotvrdjeno(boolean value) {
        this.potvrdjeno = value;
    }

    /**
     * Gets the value of the datumRealizacije property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRealizacije() {
        return datumRealizacije;
    }

    /**
     * Sets the value of the datumRealizacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRealizacije(XMLGregorianCalendar value) {
        this.datumRealizacije = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

}
